export const SET_ALL_PARAMS   = 'SET_ALL_PARAMS';

export const SET_PARAM_AMP_ATTACK   = 'SET_PARAM_AMP_ATTACK';
export const SET_PARAM_AMP_DECAY    = 'SET_PARAM_AMP_DECAY';
export const SET_PARAM_AMP_SUSTAIN  = 'SET_PARAM_AMP_SUSTAIN';
export const SET_PARAM_AMP_RELEASE  = 'SET_PARAM_AMP_RELEASE';
export const SET_PARAM_AMP_LFO_RATE     = 'SET_PARAM_AMP_LFO_RATE';
export const SET_PARAM_AMP_LFO_WIDTH    = 'SET_PARAM_AMP_LFO_WIDTH';

export const SET_PARAM_DELAY_LENGTH = 'SET_PARAM_DELAY_LENGTH';
export const SET_PARAM_DELAY_WET    = 'SET_PARAM_DELAY_WET';

export const SET_PARAM_PITCH_LFO_RATE  = 'SET_PARAM_PITCH_LFO_RATE';
export const SET_PARAM_PITCH_LFO_WIDTH = 'SET_PARAM_PITCH_LFO_WIDTH';

export const SET_PARAM_FILTER_EG_ATTACK  = 'SET_PARAM_FILTER_EG_ATTACK';
export const SET_PARAM_FILTER_EG_RELEASE = 'SET_PARAM_FILTER_EG_RELEASE';
export const SET_PARAM_FILTER_EG_FLOOR = 'SET_PARAM_FILTER_EG_FLOOR';
export const SET_PARAM_FILTER_EG_CEILING = 'SET_PARAM_FILTER_EG_CEILING';

export const SET_PARAM_FILTER_LFO_RATE  = 'SET_PARAM_FILTER_LFO_RATE';
export const SET_PARAM_FILTER_LFO_WIDTH = 'SET_PARAM_FILTER_LFO_WIDTH';

export const SET_PARAM_FILTER_CUTOFF = 'SET_PARAM_FILTER_CUTOFF';