export const SET_PARAM_AMP_ATTACK  = 'SET_PARAM_AMP_ATTACK';
export const SET_PARAM_AMP_DECAY   = 'SET_PARAM_AMP_DECAY';
export const SET_PARAM_AMP_SUSTAIN = 'SET_PARAM_AMP_SUSTAIN';
export const SET_PARAM_AMP_RELEASE = 'SET_PARAM_AMP_RELEASE';
export const SET_PARAM_LFO_RATE    = 'SET_PARAM_LFO_RATE';
export const SET_PARAM_LFO_WIDTH   = 'SET_PARAM_LFO_WIDTH';